using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DTO;
using BUS;
namespace GUI
{
    public partial class frmGiaoVien : DevExpress.XtraEditors.XtraForm
    {
        BUSGiaoVien bus_GiaoVien = new BUSGiaoVien();
        BUSBoMon bus_BoMon = new BUSBoMon();
        BUSNguoiDung bus_NguoiDung = new BUSNguoiDung();
        BUSDiaChi bus_DiaChi = new BUSDiaChi();

        public frmGiaoVien()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControlGV.DataSource = bus_GiaoVien.get_all_full_info();
           
        }

        private void labelControl6_Click(object sender, EventArgs e)
        {

        }
    }
}